### ISSUE TITLE
protobuf Decode Error

### ISSUE THREAD

**Issue by Petkomat** [understand-ai/anonymizer#29]
This is what I get after running the script

`C:\Users\...\anonymizer\anonymizer\bin\anonymize.py`

with the arguments

`--input C:\Users\...\anonymizer\images --image-output C:\Users\...\anonymizer\imagesOUT --weights C:\Users\...\anonymizer\ws`

```
Traceback (most recent call last):
  File "C:/Users/.../anonymizer/anonymizer/bin/anonymize.py", line 102, in <module>
    write_json=args.write_detections, obfuscation_parameters=args.obfuscation_kernel)
  File "C:/Users/.../anonymizer/anonymizer/bin/anonymize.py", line 84, in main
    'face': Detector(kind='face', weights_path=get_weights_path(weights_path, kind='face')),
  File "C:\Users\...\anonymizer\anonymizer\detection\detector.py", line 16, in __init__
    od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'
```

I followed the instructions (and deleted -gpu in tensorflow-gpu as requested).

-----

Also, one of the tests does not pass:

```
self = <tensorflow.python.framework.ops.Graph object at 0x000000490741A898>
obj = 'image_tensor:0', allow_tensor = True, allow_operation = False

    def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):
      """See `Graph.as_graph_element()` for details."""
      # The vast majority of this function is figuring
      # out what an API user might be doing wrong, so
      # that we can give helpful error messages.
      #
      # Ideally, it would be nice to split it up, but we
      # need context to generate nice error messages.

      if allow_tensor and allow_operation:
        types_str = "Tensor or Operation"
      elif allow_tensor:
        types_str = "Tensor"
      elif allow_operation:
        types_str = "Operation"
      else:
        raise ValueError("allow_tensor and allow_operation can't both be False.")

      temp_obj = _as_graph_element(obj)
      if temp_obj is not None:
        obj = temp_obj

      # If obj appears to be a name...
      if isinstance(obj, compat.bytes_or_text_types):
        name = compat.as_str(obj)

        if ":" in name and allow_tensor:
          # Looks like a Tensor name and can be a Tensor.
          try:
            op_name, out_n = name.split(":")
            out_n = int(out_n)
          except:
            raise ValueError("The name %s looks a like a Tensor name, but is "
                             "not a valid one. Tensor names must be of the "
                             "form \"<op_name>:<output_index>\"." % repr(name))
          if op_name in self._nodes_by_name:
            op = self._nodes_by_name[op_name]
          else:
            raise KeyError("The name %s refers to a Tensor which does not "
                           "exist. The operation, %s, does not exist in the "
>                          "graph." % (repr(name), repr(op_name)))
E           KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."


..\..\..\Anaconda3\envs\anonim\lib\site-packages\tensorflow\python\framework\ops.py:3530: KeyError
```

**Comment by philipphenkel** [comment]
We fixed an issue with the download of the weights. Automatic download should work again and additionally, I provided the links at
https://github.com/understand-ai/anonymizer/blob/master/README.md#weights

@Petkomat Please have a look.

**Comment by rary-yeki** [comment]
@Petkomat I am facing the same issue related to "The name 'image_tensor:0' refer". Were you able to fix this ?
