### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by NnaYelsel** [understand-ai/anonymizer#7]
Hello ! 

I'm trying to make this project run on CPU with windows & anaconda but I have a weird issue. 

The pytest works fine but when I'm trying to run the following command:

`python anonymizer\bin\anonymize.py --input .\input\ --image-output .\output\ --weights .\weights\`

I have the error 

```
mypath\anonymizer\anonymizer\detection\detector.py:16: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  od_graph_def.ParseFromString(serialized_graph)
```

Followed by inducted errors:

```
Anonymizing images in .\input\ and saving the anonymized images to .\output\...
  0%|                                                                                                                                       | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "anonymizer\bin\anonymize.py", line 104, in <module>
    write_json=args.write_detections, obfuscation_parameters=args.obfuscation_kernel)
  File "anonymizer\bin\anonymize.py", line 96, in main
    write_json=write_json)
  File "mypath\anonymizer\anonymizer\anonymization\anonymizer.py", line 68, in anonymize_images
    anonymized_image, detections = self.anonymize_image(image=image, detection_thresholds=detection_thresholds)
  File "mypath\anonymizer\anonymizer\anonymization\anonymizer.py", line 45, in anonymize_image
    new_boxes = detector.detect(image, detection_threshold=detection_thresholds[kind])
  File "mypath\anonymizer\anonymizer\detection\detector.py", line 40, in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
  File "mypath2\anaconda3\envs\anonymizer\lib\site-packages\tensorflow\python\framework\ops.py", line 3664, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "mypath2\anaconda3\envs\anonymizer\lib\site-packages\tensorflow\python\framework\ops.py", line 3488, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "mypath2\anaconda3\envs\anonymizer\lib\site-packages\tensorflow\python\framework\ops.py", line 3530, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

```

Have anyone an idea about the purpose of this error ? 

BR

**Comment by NnaYelsel** [comment]
Finally, the weights wasn't downloaded properly so I had to run it several time in order to obtain the two good .pb files and then it worked. 

BR
